// This file is @generated by prost-build.
/// Sandbox model stored by Navigator.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Sandbox {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub spec: ::core::option::Option<SandboxSpec>,
    #[prost(message, optional, tag = "5")]
    pub status: ::core::option::Option<SandboxStatus>,
    #[prost(enumeration = "SandboxPhase", tag = "6")]
    pub phase: i32,
}
/// Navigator-level sandbox spec.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SandboxSpec {
    #[prost(string, tag = "1")]
    pub log_level: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub agent_endpoint: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub agent_descriptor: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub agent_version: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "5")]
    pub environment: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "6")]
    pub template: ::core::option::Option<SandboxTemplate>,
    /// Required sandbox policy configuration.
    #[prost(message, optional, tag = "7")]
    pub policy: ::core::option::Option<super::super::sandbox::v1::SandboxPolicy>,
}
/// Sandbox template mapped onto Kubernetes pod template inputs.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SandboxTemplate {
    #[prost(string, tag = "1")]
    pub agent_image: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub runtime_class_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub agent_socket: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "4")]
    pub labels: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(map = "string, string", tag = "5")]
    pub annotations: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(map = "string, string", tag = "6")]
    pub environment: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "7")]
    pub resources: ::core::option::Option<::prost_types::Struct>,
    #[prost(message, optional, tag = "8")]
    pub pod_template: ::core::option::Option<::prost_types::Struct>,
    #[prost(message, optional, tag = "9")]
    pub volume_claim_templates: ::core::option::Option<::prost_types::Struct>,
}
/// Sandbox status captured from Kubernetes.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SandboxStatus {
    #[prost(string, tag = "1")]
    pub sandbox_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub agent_pod: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub agent_fd: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub sandbox_fd: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub conditions: ::prost::alloc::vec::Vec<SandboxCondition>,
}
/// Sandbox condition mirrors Kubernetes conditions.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SandboxCondition {
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub last_transition_time: ::prost::alloc::string::String,
}
/// High-level sandbox lifecycle phase.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SandboxPhase {
    Unspecified = 0,
    Provisioning = 1,
    Ready = 2,
    Error = 3,
    Deleting = 4,
    Unknown = 5,
}
impl SandboxPhase {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SANDBOX_PHASE_UNSPECIFIED",
            Self::Provisioning => "SANDBOX_PHASE_PROVISIONING",
            Self::Ready => "SANDBOX_PHASE_READY",
            Self::Error => "SANDBOX_PHASE_ERROR",
            Self::Deleting => "SANDBOX_PHASE_DELETING",
            Self::Unknown => "SANDBOX_PHASE_UNKNOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SANDBOX_PHASE_UNSPECIFIED" => Some(Self::Unspecified),
            "SANDBOX_PHASE_PROVISIONING" => Some(Self::Provisioning),
            "SANDBOX_PHASE_READY" => Some(Self::Ready),
            "SANDBOX_PHASE_ERROR" => Some(Self::Error),
            "SANDBOX_PHASE_DELETING" => Some(Self::Deleting),
            "SANDBOX_PHASE_UNKNOWN" => Some(Self::Unknown),
            _ => None,
        }
    }
}
